export const projects = [
  {
    title: 'Netflix Clone',
    description: 'My best imitation of Netflix using React and heavy use of Redux',
    img: '/portfolio_images/netflix.png',
    language: ['ReactJS', 'Redux'],
    github_url: 'https://github.com/lee44/Netflix-Clone',
    production_url: 'https://leeflix.netlify.app/',
  },
  {
    title: 'Disney+ Clone',
    description: 'A React app that mirrors the Disney+ streaming website with Firebase as the backend',
    img: '/portfolio_images/disney.png',
    language: ['ReactJS', 'Redux', 'Styled Components'],
    github_url: 'https://github.com/lee44/Disney-Clone',
    production_url: 'https://disney-clone-react.netlify.app/',
  },
  {
    title: 'Friday Crud App',
    description: 'Full Stack application that offers CRUD functionality for users',
    img: '/portfolio_images/friday-crud.jpg',
    language: ['Material-UI', 'ReactJS', 'Redux', 'Express'],
    github_url: 'https://github.com/lee44/friday',
    production_url: 'https://friday-crud.herokuapp.com/',
  },
  {
    title: 'Hacker News',
    description: 'A ReactJS app that retrieves articles containing the searched word',
    img: '/portfolio_images/hackernews.png',
    language: ['HTML5', 'CSS', 'ReactJS'],
    github_url: 'https://github.com/lee44/Hacker-News',
    production_url: 'https://hackernewsfeeds.netlify.app/',
  },
  {
    title: 'Simon Game',
    description: 'A game in which the user has to listen and repricate the given pattern of colors',
    img: '/portfolio_images/SimonGame.png',
    language: ['HTML5', 'CSS', 'JavaScript', 'JQuery'],
    github_url: 'https://github.com/lee44/FreeCodeCamp_Projects/tree/master/Simon%20Game',
    production_url: 'https://codepen.io/Lee44/pen/gReWEv?editors=1100',
  },
  {
    title: 'Cocktail DB',
    description: 'A ReactJS app that retrieves information about various cocktails from an API',
    img: '/portfolio_images/cocktail.png',
    language: ['CSS', 'HTML5', 'ReactJS'],
    github_url: 'https://github.com/lee44/Cocktail',
    production_url: 'https://cocktailsdrink.netlify.app/',
  },
  {
    title: 'Color Generator',
    description: 'Generates 10 shades and tints and allows user to Copy to Clipboard the color value',
    img: '/portfolio_images/color.png',
    language: ['CSS', 'HTML5', 'ReactJS'],
    github_url: 'https://github.com/lee44/Color-Generator',
    production_url: 'https://colortintshadegenerator.netlify.app/',
  },
  {
    title: 'Dining Advisor',
    description: 'Displays all the restaurants visible through Google Maps using a third party API',
    img: '/portfolio_images/tripadvisor.png',
    language: ['CSS', 'HTML5', 'ReactJS', 'Typescript'],
    github_url: 'https://github.com/lee44/TripAdvisor',
    production_url: 'https://diningadvisor.netlify.app/',
  },
  {
    title: 'Student Profile',
    description: 'Displays a list of student profiles for a coding assessment',
    img: '/portfolio_images/Assessment.jpg',
    language: ['ReactJS', 'TailwindCSS'],
    github_url: 'https://github.com/lee44/Assessment',
    production_url: 'https://student-profile-hathaway.netlify.app/',
  },
]
